# Data analytics - Exercise 3

Note that the assignments must be submitted as an HTML file, showing both the contents of the code cells and the outputs. You can get the notebook as an HTML file by selecting File -> Download as -> HTML. The answers to the tasks can be done in one or more code cells.

**Student's name**: Jayani Kothalawala

**Student number**: AD9680

## Inspecting DataFrame Values, Selecting Columns and Rows
In this task, we will examine the data types in a DataFrame and learn/review how to create a new DataFrame from another one. In the future, the data type might be the answer to various problem situations. It is useful to create new DataFrames, for example, when you want to examine only a part of the original DataFrame and make modifications to it.

Read the "cybersecurity_attacks.csv" file saved in exercise 2 into a DataFrame (df). If you were unable to save the file, you can also read the data from the URL https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks.csv. The first 100 rows are sufficient.

In addition to the written materials, you can find help for this task in the Pandas documentation (explore the attributes). https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

a) Print the data type of each column in the DataFrame df.

b) Print the type of the first value in the Timestamp column separately. What do you notice?
 The data type of Timestamp is a string though it has to be datetime data type. the data types are important because they affect how the data can be manipulated and analyzed. For example, if a column is of type string but contains numeric values, it may not be possible to perform mathematical operations on that column without first converting it to a numeric type. Similarly, if a column is of type datetime but is stored as a string, it may not be possible to perform date-related operations on that column without first converting it to a datetime type. Knowing the data types of each column can help prevent errors and ensure that the data is being used correctly in analysis and manipulation.


c) Create a new DataFrame (df_m) from the DataFrame df with

the columns "Timestamp", "Source IP Address", and "Attack Type"
the rows where Attack Type is "Malware"
    
![malli_dfm](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/harj3_malli_df_m.png)
    
d) Reindex the modified DataFrame df_m with default settings so that the numbering runs from 0 onwards: 0, 1, 2, ..

![malli_dfmi](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/harj3_malli_df_m_indeksoitu.png)

Scoring: 1 p

In [230]:
import pandas as pd

df = pd.read_csv('cybersecurity_attacks.csv', index_col = 0, nrows=100)

In [231]:
# Cell / answer 1.1 a)
# a) Print the data type of each column in the DataFrame df. THIS PART WILL NOT BE CHECKED IN MOODLE.

df.dtypes

Timestamp                  object
Source IP Address          object
Destination IP Address     object
Source Port                 int64
Destination Port            int64
Protocol                   object
Packet Length               int64
Packet Type                object
Traffic Type               object
Payload Data               object
Malware Indicators         object
Anomaly Scores            float64
Alerts/Warnings            object
Attack Type                object
Attack Signature           object
Action Taken               object
Severity Level             object
Device Information         object
Network Segment            object
Proxy Information          object
Firewall Logs              object
IDS/IPS Alerts             object
Log Source                 object
dtype: object

In [232]:
# Cell / answer 1.1 b)
# b) Print the type of the first value in the Timestamp column separately. (Consider and keep in mind for the future: Where do you need information about data types? What problems might arise in data manipulation and merging if you do not know the data types?)

# the data types are important because they affect how the data can be manipulated and analyzed. For example, if a column is of type string but contains numeric values, it may not be possible to perform mathematical operations on that column without first converting it to a numeric type. Similarly, if a column is of type datetime but is stored as a string, it may not be possible to perform date-related operations on that column without first converting it to a datetime type. Knowing the data types of each column can help prevent errors and ensure that the data is being used correctly in analysis and manipulation.
type(df.Timestamp[0])

str

In [233]:
# Cell / answer 1.1 c)

# c) Create a new DataFrame (df_m) from the DataFrame df
#     - columns "Timestamp", "Source IP Address", and "Attack Type"
#     - rows where Attack Type is "Malware"
# Print the first 5 rows of the new DataFrame.
df_m = df[df["Attack Type"]=="Malware"][["Timestamp","Source IP Address","Attack Type"]]
df_m.head(5)
# Note: Print the first 5 rows by writing 'df_m.head()' at the end of the cell, do not write 'print(df_m.head())'.

             Timestamp Source IP Address Attack Type
0  2023-05-30 06:33:58     103.216.15.12     Malware
1  2020-08-26 07:08:30    78.199.217.198     Malware
3  2023-07-02 10:38:46     163.42.196.10     Malware
5  2022-10-28 13:14:27     198.102.5.160     Malware
9  2021-08-15 22:29:04   114.109.149.113     Malware

In [234]:
# Cell / Answer 1.1 d)

# d) Reindex the modified DataFrame df_m with default settings so that the numbering runs from 0 onwards: 0, 1, 2, ...
# Print the first 5 rows of the reindexed DataFrame by writing 'df_m.head()' at the end of the cell.
df_m.reset_index(drop=True, inplace=True)
df_m.head(5)

             Timestamp Source IP Address Attack Type
0  2023-05-30 06:33:58     103.216.15.12     Malware
1  2020-08-26 07:08:30    78.199.217.198     Malware
2  2023-07-02 10:38:46     163.42.196.10     Malware
3  2022-10-28 13:14:27     198.102.5.160     Malware
4  2021-08-15 22:29:04   114.109.149.113     Malware

## Creating New Columns - Part 1

Sometimes it is sensible to create new columns in a DataFrame to facilitate data comparison. New columns can be used to reformat existing information, calculate descriptive features, or similar, to avoid long and potentially confusing chaining of functions, methods, and attributes, as well as errors in later processing.

In this and the next task, we will create a couple of new columns in the DataFrame df_m from the previous task, which will later be used to enrich the data with country information.

Recall the binary format of IPv4 addresses, subnet mask, and CIDR notation if they are not fresh in your memory.
Familiarize yourself with Python's ipaddress library, which can be used to format and compare IP addresses. https://pypi.org/project/ipaddress/ and https://docs.python.org/3/library/ipaddress.html. Install the ipaddress library.
Create a new column "Source IP Address type(ip)" in the DataFrame df_m from the previous task, where the IP address is converted from a string to IPv4Address format. (Hint: apply https://ajota.pages.labranet.jamk.fi/kyberuhkatieto-ja-data-analytiikka/Kirjalliset%20materiaalit%20suomeksi/10-Datan_laatu_ja_tunnusluvut/#apply-applymap-map) If you did not create the DataFrame df_m in the previous task, you can read it from the URL https://student.labranet.jamk.fi/~ajota/Datasets/cybersecurity_attacks_time_ip_attype.csv
Print the first value and its type from the "Source IP Address type(ip)" column in the DataFrame df_m.

Scoring: 1 p

![malli_osa1](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/harj3_ipv4_malli.png)

In [235]:
# pip install ...
import ipaddress

In [236]:
# Cell / answer 1.2
# Print out the type of 'Source IP Address type(ip)' columns firts value-.
df_m["Source IP Address type(ip)"] = df_m["Source IP Address"].apply(lambda x: ipaddress.ip_address(x))
type(df_m["Source IP Address type(ip)"][0])

ipaddress.IPv4Address

## Creating New Columns - Part 2

In this section, we will create a helper column "network," which will eventually be used in the final part of the exercise to link the corresponding country information to the IP address in the DataFrame.

The file geoip2-ipv4.csv lists the continents and countries of IP addresses.

Read the data into a DataFrame df_geo from the URL https://student.labranet.jamk.fi/~ajota/Datasets/geoip2-ipv4.csv
Create a new column "network" in the DataFrame df_m, which contains information about which networks listed in the df_geo DataFrame the IP belongs to. The file may not have information on all networks. Use/set missing values as NumPy's NaN values.
Print the first 5 rows of the DataFrame.
You can start solving the task as follows, but other solutions that create the network column in the DataFrame are also acceptable.

Save the "network" values from the DataFrame df_geo into a list.
Define a function that checks the IP against the networks in the list. If the IP belongs to the network mask, the function returns the respective network.
Perform the check for the IPs in the DataFrame df_m.

Scoring: 1 p

Below is a screenshot of the desired outcome:

![malli](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/malli_add_network_column.png)

In [237]:
# Read the geo-information
df_geo = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/geoip2-ipv4.csv')

In [238]:
# Codes in this cell...
import numpy as np
list1 = df_geo["network"].tolist()
networks = [ipaddress.ip_network(net) for net in list1]
def find_network(ip):
    for net in networks:
        if ip in net:
            return net
    return np.nan
df_m["network"] = df_m["Source IP Address type(ip)"].apply(find_network)
df_m.head(5)

,Timestamp,Source IP Address,Attack Type,Source IP Address type(ip),network
0,2023-05-30 06:33:58,103.216.15.12,Malware,103.216.15.12,NaN
1,2020-08-26 07:08:30,78.199.217.198,Malware,78.199.217.198,78.192.0.0/10
2,2023-07-02 10:38:46,163.42.196.10,Malware,163.42.196.10,163.42.0.0/15
3,2022-10-28 13:14:27,198.102.5.160,Malware,198.102.5.160,198.102.0.0/17
4,2021-08-15 22:29:04,114.109.149.113,Malware,114.109.149.113,114.109.0.0/16

In [239]:
# Cell / answer 1.3

# Last run this cell's code. As a result there should be first 5 rows from the screenshots Data Frame.

df_m.head(5)

,Timestamp,Source IP Address,Attack Type,Source IP Address type(ip),network
0,2023-05-30 06:33:58,103.216.15.12,Malware,103.216.15.12,NaN
1,2020-08-26 07:08:30,78.199.217.198,Malware,78.199.217.198,78.192.0.0/10
2,2023-07-02 10:38:46,163.42.196.10,Malware,163.42.196.10,163.42.0.0/15
3,2022-10-28 13:14:27,198.102.5.160,Malware,198.102.5.160,198.102.0.0/17
4,2021-08-15 22:29:04,114.109.149.113,Malware,114.109.149.113,114.109.0.0/16

## Merging Data

Enrich the DataFrame df_m by merging it with country information from the DataFrame df_geo. If you were unable to create the network column in the previous step, you can read the data from this URL: 'https://student.labranet.jamk.fi/~ajota/Datasets/df_m_malware_ip_and_network.csv'.

- Specify what the merge will be based on.
- Specify how the merge will be done.
    - The final result should not include countries from which there are no attacks. (In other words, it should not include unnecessary extra rows where Timestamp, Source IP Address, Attack Type, and Source IP Address type(ip) would be NaN)
    - Attacks (rows in the DataFrame df_m) for which country information is not found should not be dropped.
- Consider the type of the column on which the merge is based. You may still need to make modifications to perform the merge.

Finally, print the number of rows in the merged DataFrame. Print the columns of the DataFrame.

Scoring: 1 p

Below is an example of the desired outcome:
![malli](https://student.labranet.jamk.fi/~ajota/Data-analytics/images/malli_df_m_df_geo_merged.png)

In [240]:
# Geographic information
dfg = pd.read_csv('https://student.labranet.jamk.fi/~ajota/Datasets/geoip2-ipv4.csv')

In [241]:
# Codes in this cell...
df_m["network"] = df_m["network"].astype(str)
df_geo["network"] = df_geo["network"].astype(str)
df_merged = pd.merge(
    df_m,
    df_geo,
    on="network",     # merge key
    how="left"        # keep all attacks even if no country found
)
df_merged.head(5)

,Timestamp,Source IP Address,Attack Type,Source IP Address type(ip),network,geoname_id,continent_code,continent_name,country_iso_code,country_name,is_anonymous_proxy,is_satellite_provider
0,2023-05-30 06:33:58,103.216.15.12,Malware,103.216.15.12,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-08-26 07:08:30,78.199.217.198,Malware,78.199.217.198,78.192.0.0/10,3017382.0,EU,Europe,FR,France,False,False
2,2023-07-02 10:38:46,163.42.196.10,Malware,163.42.196.10,163.42.0.0/15,1861060.0,AS,Asia,JP,Japan,False,False
3,2022-10-28 13:14:27,198.102.5.160,Malware,198.102.5.160,198.102.0.0/17,6252001.0,NaN,North America,US,United States,False,False
4,2021-08-15 22:29:04,114.109.149.113,Malware,114.109.149.113,114.109.0.0/16,1605651.0,AS,Asia,TH,Thailand,False,False

In [248]:
# Cell 1.4 a)
# Print the number of rows in the resulting DataFrame. The DataFrame is named 'df'.

len(df_merged)

38

In [251]:
# Cell 1.4 b)
# Print the columns of the resulting DataFrame. The DataFrame is named 'df', change it if you used a different name.

df_merged.columns

Index(['Timestamp', 'Source IP Address', 'Attack Type',
       'Source IP Address type(ip)', 'network', 'geoname_id', 'continent_code',
       'continent_name', 'country_iso_code', 'country_name',
       'is_anonymous_proxy', 'is_satellite_provider'],
      dtype='object')

In [250]:
df.head()

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Attack Type,Attack Signature,Action Taken,Severity Level,Device Information,Network Segment,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Malware,Known Pattern B,Logged,Low,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,150.9.97.135,Log Data,NaN,Server
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Malware,Known Pattern A,Blocked,Low,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,NaN,Log Data,NaN,Firewall
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,DDoS,Known Pattern B,Ignored,Low,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,114.133.48.179,Log Data,Alert Data,Firewall
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Malware,Known Pattern B,Blocked,Medium,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,NaN,NaN,Alert Data,Firewall
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,DDoS,Known Pattern B,Blocked,Low,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,149.6.110.119,NaN,Alert Data,Firewall